name: accounts - CI
on:
  workflow_call:
    inputs:
      event:
        description: "Webhook event payload of accounts repository"
        required: true
        type: string
    secrets:
      PAT:
        description: "Personal access token that have access to accounts repository"
        required: true
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: ${{ fromJSON(inputs.event).repository.full_name }}
          ref: ${{ fromJSON(inputs.event).ref }}
          token: ${{ secrets.PAT }}
      - uses: actions/setup-node@v3
      - name: Build
        run: yarn build
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: ${{ fromJSON(inputs.event).repository.full_name }}
          ref: ${{ fromJSON(inputs.event).ref }}
          token: ${{ secrets.PAT }}
      - uses: actions/setup-node@v3
      - name: Lint
        run: yarn lint