name: Workflow router
on:
  repository_dispatch: {}
jobs:
  accounts-ci:
    name: Accounts - CI
    uses: ./.github/workflows/accounts-ci.yaml
    if: ${{ github.event.client_payload.event.repository.full_name == 'webzyno/accounts' }}
    with:
      event: ${{ toJSON(github.event.client_payload.event) }}
    secrets:
      PAT: ${{ secrets.PAT }}
