name: Workflow router
on:
  repository_dispatch: {}

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.event.action }}
      - run: echo ${{ github.event.client_payload }}
